project:
  type: book

book:
  title: "The book of seahtrue"
  author: "Vincent de Boer"
  date: "10/4/2023"

  chapters:
    - index.qmd
    - part: swim.qmd
      chapters:
      - swim_intro.qmd
      - swim_cars.qmd
      - swim_seahorse.qmd
      - references.qmd
    - part: intro.qmd
      chapters:
        - intro.qmd

  sidebar:
    search: true
    tools:
      - icon: github
        href: https://github.com/vcjdeboer

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual

filters:
  - webr

